source 'https://github.com/TAPart/TASpace.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'AFNdemo_Example' do
  pod 'AFNdemo', :path => '../'

  target 'AFNdemo_Tests' do
    inherit! :search_paths

    
  end
end
